server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cart?useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.244.100
  task:
    execution:
      thread-name-prefix: gmall-cart-
      pool:
        core-size: 100
        max-size: 500
        queue-capacity: 2000
        keep-alive: 60s
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    host: 192.168.244.100
    port: 5672
    virtual-host: /gmall
    username: nimodo
    password: 123456
    listener:
      simple:
        prefetch: 1
        concurrency: 6
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
jwt:
  cookieName: GMALL-TOKEN
  pubKeyPath: C:\project-0212\rsa\rsa.pub
  userKey: user-key
  expire: 864000