server:
  port: 8866
spring:
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: oms-route
          uri: lb://osm-service
          predicates:
            - Path=/oms/**
        - id: index-route # 为同步请求配置的路由
          uri: lb://index-service
          predicates:
            - Host=gmall.com, www.gmall.com
          filters:
            - Auth=/xxxx,/yyyy,/zzzz,/tttt
            - AddResponseHeader=xxxx,yyyy
        - id: index-route2 # 为异步请求配置的路由
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com

jwt:
  cookieName: GMALL-TOKEN
  token: token
  pubKeyPath: C:\project-0212\rsa\rsa.pub
